modLoader="javafml" 
loaderVersion="[34,)"
issueTrackerURL="https://github.com/owmii/Lollipop/issues"
license="LGPLv3"

[[mods]]
modId="lollipop"
version="${file.jarVersion}"
displayName="Lollipop"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lollipop"
authors="owmii"
description='''
A Library mod.
'''

[[dependencies.lollipop]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.2,)"
    ordering="NONE"
    side="BOTH"